name: Demo CI workflow
on: 
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  hello:
    name: My Hello Job
    runs-on: ubuntu-latest
    steps:
        - name: Print hello world
          run: echo "Hello World"
        - name: Second Step
          run: echo "second"
  goodbye:
    name: My Goodbye Job
    needs: [hello, test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "goodbye"
        name: Say by bye
  test:
    name: Test the Python Package
    runs-on: ${{matrix.platform}}
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.14"
        platform: 
          - ubuntu-latest
          - alpine-latest
        include: 
          - python-version: "3.13"
            platform: macos-15

    steps:
        - name: Set up git repo
          uses: actions/checkout@v6
        - name: Set up specific python version
          uses: actions/setup-python@v6
          with:
            python-version: ${{matrix.python-version}}
        - name: Install the package
          run: pip install .[test]
        - name: Run the tests
          run: pytest -vv